version: '3'
services:
  oaw:
    build:
      context: ../..
      dockerfile: ./deployment/docker/Dockerfile
    depends_on:
      - mysql
    restart: on-failure:5
    ports:
      - "8080:8080"
    expose:
      - '8080'
    links:
      - mysql
    environment:
      DBCONN_RETRY_COUNT: '12'
      DBCONN_RETRY_DELAY: '5'

  proxy:
    build:
      context: ../../oaw/docker/proxy
      dockerfile: Dockerfile
    ports:
      - "18088:18088"
    command: node /opt/proxy/index.js
    restart: always
    container_name: oaw_js_proxy
  

  renderer:
    build:
      context: ../../oaw/docker/renderer
      dockerfile: Dockerfile
    command: node /opt/prerender/server.js
    privileged: true
    restart: always


  nginx:
    image: nginx:1.13.8-alpine
    volumes:
      - ../../oaw/docker/nginx/reverse.conf:/etc/nginx/conf.d/default.conf
      - ../../oaw/docker/nginx/certs/server.crt:/etc/nginx/ssl/server.crt
      - ../../oaw/docker/nginx/certs/server.key:/etc/nginx/ssl/server.key
    links:
      - renderer
    restart: always


  mysql:
    build:
      context: ..
      dockerfile: ./docker/database/testdb-dockerfile
    restart: always
    environment:
      #MYSQL_DATABASE: 'oaw'
      #MYSQL_USER: 'root'
      #MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
      - '33060:33060'
    expose:
      - '3306'
      - '33060'
    